#ifndef INCLUDED_CYFITTER_H
#define INCLUDED_CYFITTER_H
#include "cydevice_trm.h"

/* ESP_rx */
#define ESP_rx__0__DM__MASK 0x7000u
#define ESP_rx__0__DM__SHIFT 12
#define ESP_rx__0__DR CYREG_PRT0_DR
#define ESP_rx__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define ESP_rx__0__HSIOM_MASK 0x000F0000u
#define ESP_rx__0__HSIOM_SHIFT 16u
#define ESP_rx__0__INTCFG CYREG_PRT0_INTCFG
#define ESP_rx__0__INTSTAT CYREG_PRT0_INTSTAT
#define ESP_rx__0__MASK 0x10u
#define ESP_rx__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define ESP_rx__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define ESP_rx__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define ESP_rx__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define ESP_rx__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define ESP_rx__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define ESP_rx__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define ESP_rx__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define ESP_rx__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define ESP_rx__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define ESP_rx__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define ESP_rx__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define ESP_rx__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define ESP_rx__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define ESP_rx__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define ESP_rx__0__PC CYREG_PRT0_PC
#define ESP_rx__0__PC2 CYREG_PRT0_PC2
#define ESP_rx__0__PORT 0u
#define ESP_rx__0__PS CYREG_PRT0_PS
#define ESP_rx__0__SHIFT 4
#define ESP_rx__DR CYREG_PRT0_DR
#define ESP_rx__INTCFG CYREG_PRT0_INTCFG
#define ESP_rx__INTSTAT CYREG_PRT0_INTSTAT
#define ESP_rx__MASK 0x10u
#define ESP_rx__PA__CFG0 CYREG_UDB_PA0_CFG0
#define ESP_rx__PA__CFG1 CYREG_UDB_PA0_CFG1
#define ESP_rx__PA__CFG10 CYREG_UDB_PA0_CFG10
#define ESP_rx__PA__CFG11 CYREG_UDB_PA0_CFG11
#define ESP_rx__PA__CFG12 CYREG_UDB_PA0_CFG12
#define ESP_rx__PA__CFG13 CYREG_UDB_PA0_CFG13
#define ESP_rx__PA__CFG14 CYREG_UDB_PA0_CFG14
#define ESP_rx__PA__CFG2 CYREG_UDB_PA0_CFG2
#define ESP_rx__PA__CFG3 CYREG_UDB_PA0_CFG3
#define ESP_rx__PA__CFG4 CYREG_UDB_PA0_CFG4
#define ESP_rx__PA__CFG5 CYREG_UDB_PA0_CFG5
#define ESP_rx__PA__CFG6 CYREG_UDB_PA0_CFG6
#define ESP_rx__PA__CFG7 CYREG_UDB_PA0_CFG7
#define ESP_rx__PA__CFG8 CYREG_UDB_PA0_CFG8
#define ESP_rx__PA__CFG9 CYREG_UDB_PA0_CFG9
#define ESP_rx__PC CYREG_PRT0_PC
#define ESP_rx__PC2 CYREG_PRT0_PC2
#define ESP_rx__PORT 0u
#define ESP_rx__PS CYREG_PRT0_PS
#define ESP_rx__SHIFT 4

/* ESP_SCB */
#define ESP_SCB__BIST_CONTROL CYREG_SCB1_BIST_CONTROL
#define ESP_SCB__BIST_DATA CYREG_SCB1_BIST_DATA
#define ESP_SCB__CTRL CYREG_SCB1_CTRL
#define ESP_SCB__EZ_DATA00 CYREG_SCB1_EZ_DATA00
#define ESP_SCB__EZ_DATA01 CYREG_SCB1_EZ_DATA01
#define ESP_SCB__EZ_DATA02 CYREG_SCB1_EZ_DATA02
#define ESP_SCB__EZ_DATA03 CYREG_SCB1_EZ_DATA03
#define ESP_SCB__EZ_DATA04 CYREG_SCB1_EZ_DATA04
#define ESP_SCB__EZ_DATA05 CYREG_SCB1_EZ_DATA05
#define ESP_SCB__EZ_DATA06 CYREG_SCB1_EZ_DATA06
#define ESP_SCB__EZ_DATA07 CYREG_SCB1_EZ_DATA07
#define ESP_SCB__EZ_DATA08 CYREG_SCB1_EZ_DATA08
#define ESP_SCB__EZ_DATA09 CYREG_SCB1_EZ_DATA09
#define ESP_SCB__EZ_DATA10 CYREG_SCB1_EZ_DATA10
#define ESP_SCB__EZ_DATA11 CYREG_SCB1_EZ_DATA11
#define ESP_SCB__EZ_DATA12 CYREG_SCB1_EZ_DATA12
#define ESP_SCB__EZ_DATA13 CYREG_SCB1_EZ_DATA13
#define ESP_SCB__EZ_DATA14 CYREG_SCB1_EZ_DATA14
#define ESP_SCB__EZ_DATA15 CYREG_SCB1_EZ_DATA15
#define ESP_SCB__EZ_DATA16 CYREG_SCB1_EZ_DATA16
#define ESP_SCB__EZ_DATA17 CYREG_SCB1_EZ_DATA17
#define ESP_SCB__EZ_DATA18 CYREG_SCB1_EZ_DATA18
#define ESP_SCB__EZ_DATA19 CYREG_SCB1_EZ_DATA19
#define ESP_SCB__EZ_DATA20 CYREG_SCB1_EZ_DATA20
#define ESP_SCB__EZ_DATA21 CYREG_SCB1_EZ_DATA21
#define ESP_SCB__EZ_DATA22 CYREG_SCB1_EZ_DATA22
#define ESP_SCB__EZ_DATA23 CYREG_SCB1_EZ_DATA23
#define ESP_SCB__EZ_DATA24 CYREG_SCB1_EZ_DATA24
#define ESP_SCB__EZ_DATA25 CYREG_SCB1_EZ_DATA25
#define ESP_SCB__EZ_DATA26 CYREG_SCB1_EZ_DATA26
#define ESP_SCB__EZ_DATA27 CYREG_SCB1_EZ_DATA27
#define ESP_SCB__EZ_DATA28 CYREG_SCB1_EZ_DATA28
#define ESP_SCB__EZ_DATA29 CYREG_SCB1_EZ_DATA29
#define ESP_SCB__EZ_DATA30 CYREG_SCB1_EZ_DATA30
#define ESP_SCB__EZ_DATA31 CYREG_SCB1_EZ_DATA31
#define ESP_SCB__I2C_CFG CYREG_SCB1_I2C_CFG
#define ESP_SCB__I2C_CTRL CYREG_SCB1_I2C_CTRL
#define ESP_SCB__I2C_M_CMD CYREG_SCB1_I2C_M_CMD
#define ESP_SCB__I2C_S_CMD CYREG_SCB1_I2C_S_CMD
#define ESP_SCB__I2C_STATUS CYREG_SCB1_I2C_STATUS
#define ESP_SCB__INTR_CAUSE CYREG_SCB1_INTR_CAUSE
#define ESP_SCB__INTR_I2C_EC CYREG_SCB1_INTR_I2C_EC
#define ESP_SCB__INTR_I2C_EC_MASK CYREG_SCB1_INTR_I2C_EC_MASK
#define ESP_SCB__INTR_I2C_EC_MASKED CYREG_SCB1_INTR_I2C_EC_MASKED
#define ESP_SCB__INTR_M CYREG_SCB1_INTR_M
#define ESP_SCB__INTR_M_MASK CYREG_SCB1_INTR_M_MASK
#define ESP_SCB__INTR_M_MASKED CYREG_SCB1_INTR_M_MASKED
#define ESP_SCB__INTR_M_SET CYREG_SCB1_INTR_M_SET
#define ESP_SCB__INTR_RX CYREG_SCB1_INTR_RX
#define ESP_SCB__INTR_RX_MASK CYREG_SCB1_INTR_RX_MASK
#define ESP_SCB__INTR_RX_MASKED CYREG_SCB1_INTR_RX_MASKED
#define ESP_SCB__INTR_RX_SET CYREG_SCB1_INTR_RX_SET
#define ESP_SCB__INTR_S CYREG_SCB1_INTR_S
#define ESP_SCB__INTR_S_MASK CYREG_SCB1_INTR_S_MASK
#define ESP_SCB__INTR_S_MASKED CYREG_SCB1_INTR_S_MASKED
#define ESP_SCB__INTR_S_SET CYREG_SCB1_INTR_S_SET
#define ESP_SCB__INTR_SPI_EC CYREG_SCB1_INTR_SPI_EC
#define ESP_SCB__INTR_SPI_EC_MASK CYREG_SCB1_INTR_SPI_EC_MASK
#define ESP_SCB__INTR_SPI_EC_MASKED CYREG_SCB1_INTR_SPI_EC_MASKED
#define ESP_SCB__INTR_TX CYREG_SCB1_INTR_TX
#define ESP_SCB__INTR_TX_MASK CYREG_SCB1_INTR_TX_MASK
#define ESP_SCB__INTR_TX_MASKED CYREG_SCB1_INTR_TX_MASKED
#define ESP_SCB__INTR_TX_SET CYREG_SCB1_INTR_TX_SET
#define ESP_SCB__RX_CTRL CYREG_SCB1_RX_CTRL
#define ESP_SCB__RX_FIFO_CTRL CYREG_SCB1_RX_FIFO_CTRL
#define ESP_SCB__RX_FIFO_RD CYREG_SCB1_RX_FIFO_RD
#define ESP_SCB__RX_FIFO_RD_SILENT CYREG_SCB1_RX_FIFO_RD_SILENT
#define ESP_SCB__RX_FIFO_STATUS CYREG_SCB1_RX_FIFO_STATUS
#define ESP_SCB__RX_MATCH CYREG_SCB1_RX_MATCH
#define ESP_SCB__SPI_CTRL CYREG_SCB1_SPI_CTRL
#define ESP_SCB__SPI_STATUS CYREG_SCB1_SPI_STATUS
#define ESP_SCB__SS0_POSISTION 0u
#define ESP_SCB__SS1_POSISTION 1u
#define ESP_SCB__SS2_POSISTION 2u
#define ESP_SCB__SS3_POSISTION 3u
#define ESP_SCB__STATUS CYREG_SCB1_STATUS
#define ESP_SCB__TX_CTRL CYREG_SCB1_TX_CTRL
#define ESP_SCB__TX_FIFO_CTRL CYREG_SCB1_TX_FIFO_CTRL
#define ESP_SCB__TX_FIFO_STATUS CYREG_SCB1_TX_FIFO_STATUS
#define ESP_SCB__TX_FIFO_WR CYREG_SCB1_TX_FIFO_WR
#define ESP_SCB__UART_CTRL CYREG_SCB1_UART_CTRL
#define ESP_SCB__UART_RX_CTRL CYREG_SCB1_UART_RX_CTRL
#define ESP_SCB__UART_RX_STATUS CYREG_SCB1_UART_RX_STATUS
#define ESP_SCB__UART_TX_CTRL CYREG_SCB1_UART_TX_CTRL

/* ESP_SCB_IRQ */
#define ESP_SCB_IRQ__INTC_CLR_EN_REG CYREG_CM0_ICER
#define ESP_SCB_IRQ__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define ESP_SCB_IRQ__INTC_MASK 0x800u
#define ESP_SCB_IRQ__INTC_NUMBER 11u
#define ESP_SCB_IRQ__INTC_PRIOR_MASK 0xC0000000u
#define ESP_SCB_IRQ__INTC_PRIOR_NUM 3u
#define ESP_SCB_IRQ__INTC_PRIOR_REG CYREG_CM0_IPR2
#define ESP_SCB_IRQ__INTC_SET_EN_REG CYREG_CM0_ISER
#define ESP_SCB_IRQ__INTC_SET_PD_REG CYREG_CM0_ISPR

/* ESP_SCBCLK */
#define ESP_SCBCLK__DIVIDER_MASK 0x0000FFFFu
#define ESP_SCBCLK__ENABLE CYREG_CLK_DIVIDER_A00
#define ESP_SCBCLK__ENABLE_MASK 0x80000000u
#define ESP_SCBCLK__MASK 0x80000000u
#define ESP_SCBCLK__REGISTER CYREG_CLK_DIVIDER_A00

/* ESP_tx */
#define ESP_tx__0__DM__MASK 0x38000u
#define ESP_tx__0__DM__SHIFT 15
#define ESP_tx__0__DR CYREG_PRT0_DR
#define ESP_tx__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define ESP_tx__0__HSIOM_MASK 0x00F00000u
#define ESP_tx__0__HSIOM_SHIFT 20u
#define ESP_tx__0__INTCFG CYREG_PRT0_INTCFG
#define ESP_tx__0__INTSTAT CYREG_PRT0_INTSTAT
#define ESP_tx__0__MASK 0x20u
#define ESP_tx__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define ESP_tx__0__OUT_SEL_SHIFT 10u
#define ESP_tx__0__OUT_SEL_VAL -1u
#define ESP_tx__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define ESP_tx__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define ESP_tx__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define ESP_tx__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define ESP_tx__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define ESP_tx__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define ESP_tx__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define ESP_tx__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define ESP_tx__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define ESP_tx__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define ESP_tx__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define ESP_tx__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define ESP_tx__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define ESP_tx__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define ESP_tx__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define ESP_tx__0__PC CYREG_PRT0_PC
#define ESP_tx__0__PC2 CYREG_PRT0_PC2
#define ESP_tx__0__PORT 0u
#define ESP_tx__0__PS CYREG_PRT0_PS
#define ESP_tx__0__SHIFT 5
#define ESP_tx__DR CYREG_PRT0_DR
#define ESP_tx__INTCFG CYREG_PRT0_INTCFG
#define ESP_tx__INTSTAT CYREG_PRT0_INTSTAT
#define ESP_tx__MASK 0x20u
#define ESP_tx__PA__CFG0 CYREG_UDB_PA0_CFG0
#define ESP_tx__PA__CFG1 CYREG_UDB_PA0_CFG1
#define ESP_tx__PA__CFG10 CYREG_UDB_PA0_CFG10
#define ESP_tx__PA__CFG11 CYREG_UDB_PA0_CFG11
#define ESP_tx__PA__CFG12 CYREG_UDB_PA0_CFG12
#define ESP_tx__PA__CFG13 CYREG_UDB_PA0_CFG13
#define ESP_tx__PA__CFG14 CYREG_UDB_PA0_CFG14
#define ESP_tx__PA__CFG2 CYREG_UDB_PA0_CFG2
#define ESP_tx__PA__CFG3 CYREG_UDB_PA0_CFG3
#define ESP_tx__PA__CFG4 CYREG_UDB_PA0_CFG4
#define ESP_tx__PA__CFG5 CYREG_UDB_PA0_CFG5
#define ESP_tx__PA__CFG6 CYREG_UDB_PA0_CFG6
#define ESP_tx__PA__CFG7 CYREG_UDB_PA0_CFG7
#define ESP_tx__PA__CFG8 CYREG_UDB_PA0_CFG8
#define ESP_tx__PA__CFG9 CYREG_UDB_PA0_CFG9
#define ESP_tx__PC CYREG_PRT0_PC
#define ESP_tx__PC2 CYREG_PRT0_PC2
#define ESP_tx__PORT 0u
#define ESP_tx__PS CYREG_PRT0_PS
#define ESP_tx__SHIFT 5

/* Strip_0 */
#define Strip_0__0__DM__MASK 0x1C0000u
#define Strip_0__0__DM__SHIFT 18
#define Strip_0__0__DR CYREG_PRT1_DR
#define Strip_0__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Strip_0__0__HSIOM_MASK 0x0F000000u
#define Strip_0__0__HSIOM_SHIFT 24u
#define Strip_0__0__INTCFG CYREG_PRT1_INTCFG
#define Strip_0__0__INTSTAT CYREG_PRT1_INTSTAT
#define Strip_0__0__MASK 0x40u
#define Strip_0__0__OUT_SEL CYREG_UDB_PA1_CFG10
#define Strip_0__0__OUT_SEL_SHIFT 12u
#define Strip_0__0__OUT_SEL_VAL 1u
#define Strip_0__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Strip_0__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Strip_0__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Strip_0__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Strip_0__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Strip_0__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Strip_0__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Strip_0__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Strip_0__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Strip_0__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Strip_0__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Strip_0__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Strip_0__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Strip_0__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Strip_0__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Strip_0__0__PC CYREG_PRT1_PC
#define Strip_0__0__PC2 CYREG_PRT1_PC2
#define Strip_0__0__PORT 1u
#define Strip_0__0__PS CYREG_PRT1_PS
#define Strip_0__0__SHIFT 6
#define Strip_0__DR CYREG_PRT1_DR
#define Strip_0__INTCFG CYREG_PRT1_INTCFG
#define Strip_0__INTSTAT CYREG_PRT1_INTSTAT
#define Strip_0__MASK 0x40u
#define Strip_0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Strip_0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Strip_0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Strip_0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Strip_0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Strip_0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Strip_0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Strip_0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Strip_0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Strip_0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Strip_0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Strip_0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Strip_0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Strip_0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Strip_0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Strip_0__PC CYREG_PRT1_PC
#define Strip_0__PC2 CYREG_PRT1_PC2
#define Strip_0__PORT 1u
#define Strip_0__PS CYREG_PRT1_PS
#define Strip_0__SHIFT 6

/* Strip_1 */
#define Strip_1__0__DM__MASK 0x38000u
#define Strip_1__0__DM__SHIFT 15
#define Strip_1__0__DR CYREG_PRT1_DR
#define Strip_1__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Strip_1__0__HSIOM_MASK 0x00F00000u
#define Strip_1__0__HSIOM_SHIFT 20u
#define Strip_1__0__INTCFG CYREG_PRT1_INTCFG
#define Strip_1__0__INTSTAT CYREG_PRT1_INTSTAT
#define Strip_1__0__MASK 0x20u
#define Strip_1__0__OUT_SEL CYREG_UDB_PA1_CFG10
#define Strip_1__0__OUT_SEL_SHIFT 10u
#define Strip_1__0__OUT_SEL_VAL 0u
#define Strip_1__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Strip_1__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Strip_1__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Strip_1__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Strip_1__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Strip_1__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Strip_1__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Strip_1__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Strip_1__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Strip_1__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Strip_1__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Strip_1__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Strip_1__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Strip_1__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Strip_1__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Strip_1__0__PC CYREG_PRT1_PC
#define Strip_1__0__PC2 CYREG_PRT1_PC2
#define Strip_1__0__PORT 1u
#define Strip_1__0__PS CYREG_PRT1_PS
#define Strip_1__0__SHIFT 5
#define Strip_1__DR CYREG_PRT1_DR
#define Strip_1__INTCFG CYREG_PRT1_INTCFG
#define Strip_1__INTSTAT CYREG_PRT1_INTSTAT
#define Strip_1__MASK 0x20u
#define Strip_1__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Strip_1__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Strip_1__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Strip_1__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Strip_1__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Strip_1__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Strip_1__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Strip_1__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Strip_1__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Strip_1__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Strip_1__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Strip_1__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Strip_1__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Strip_1__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Strip_1__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Strip_1__PC CYREG_PRT1_PC
#define Strip_1__PC2 CYREG_PRT1_PC2
#define Strip_1__PORT 1u
#define Strip_1__PS CYREG_PRT1_PS
#define Strip_1__SHIFT 5

/* Strip_2 */
#define Strip_2__0__DM__MASK 0x7000u
#define Strip_2__0__DM__SHIFT 12
#define Strip_2__0__DR CYREG_PRT1_DR
#define Strip_2__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Strip_2__0__HSIOM_MASK 0x000F0000u
#define Strip_2__0__HSIOM_SHIFT 16u
#define Strip_2__0__INTCFG CYREG_PRT1_INTCFG
#define Strip_2__0__INTSTAT CYREG_PRT1_INTSTAT
#define Strip_2__0__MASK 0x10u
#define Strip_2__0__OUT_SEL CYREG_UDB_PA1_CFG10
#define Strip_2__0__OUT_SEL_SHIFT 8u
#define Strip_2__0__OUT_SEL_VAL 3u
#define Strip_2__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Strip_2__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Strip_2__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Strip_2__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Strip_2__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Strip_2__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Strip_2__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Strip_2__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Strip_2__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Strip_2__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Strip_2__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Strip_2__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Strip_2__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Strip_2__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Strip_2__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Strip_2__0__PC CYREG_PRT1_PC
#define Strip_2__0__PC2 CYREG_PRT1_PC2
#define Strip_2__0__PORT 1u
#define Strip_2__0__PS CYREG_PRT1_PS
#define Strip_2__0__SHIFT 4
#define Strip_2__DR CYREG_PRT1_DR
#define Strip_2__INTCFG CYREG_PRT1_INTCFG
#define Strip_2__INTSTAT CYREG_PRT1_INTSTAT
#define Strip_2__MASK 0x10u
#define Strip_2__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Strip_2__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Strip_2__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Strip_2__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Strip_2__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Strip_2__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Strip_2__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Strip_2__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Strip_2__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Strip_2__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Strip_2__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Strip_2__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Strip_2__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Strip_2__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Strip_2__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Strip_2__PC CYREG_PRT1_PC
#define Strip_2__PC2 CYREG_PRT1_PC2
#define Strip_2__PORT 1u
#define Strip_2__PS CYREG_PRT1_PS
#define Strip_2__SHIFT 4

/* Strip_3 */
#define Strip_3__0__DM__MASK 0xE00u
#define Strip_3__0__DM__SHIFT 9
#define Strip_3__0__DR CYREG_PRT1_DR
#define Strip_3__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Strip_3__0__HSIOM_MASK 0x0000F000u
#define Strip_3__0__HSIOM_SHIFT 12u
#define Strip_3__0__INTCFG CYREG_PRT1_INTCFG
#define Strip_3__0__INTSTAT CYREG_PRT1_INTSTAT
#define Strip_3__0__MASK 0x08u
#define Strip_3__0__OUT_SEL CYREG_UDB_PA1_CFG10
#define Strip_3__0__OUT_SEL_SHIFT 6u
#define Strip_3__0__OUT_SEL_VAL 0u
#define Strip_3__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Strip_3__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Strip_3__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Strip_3__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Strip_3__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Strip_3__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Strip_3__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Strip_3__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Strip_3__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Strip_3__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Strip_3__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Strip_3__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Strip_3__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Strip_3__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Strip_3__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Strip_3__0__PC CYREG_PRT1_PC
#define Strip_3__0__PC2 CYREG_PRT1_PC2
#define Strip_3__0__PORT 1u
#define Strip_3__0__PS CYREG_PRT1_PS
#define Strip_3__0__SHIFT 3
#define Strip_3__DR CYREG_PRT1_DR
#define Strip_3__INTCFG CYREG_PRT1_INTCFG
#define Strip_3__INTSTAT CYREG_PRT1_INTSTAT
#define Strip_3__MASK 0x08u
#define Strip_3__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Strip_3__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Strip_3__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Strip_3__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Strip_3__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Strip_3__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Strip_3__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Strip_3__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Strip_3__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Strip_3__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Strip_3__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Strip_3__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Strip_3__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Strip_3__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Strip_3__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Strip_3__PC CYREG_PRT1_PC
#define Strip_3__PC2 CYREG_PRT1_PC2
#define Strip_3__PORT 1u
#define Strip_3__PS CYREG_PRT1_PS
#define Strip_3__SHIFT 3

/* Strip_4 */
#define Strip_4__0__DM__MASK 0x1C0u
#define Strip_4__0__DM__SHIFT 6
#define Strip_4__0__DR CYREG_PRT1_DR
#define Strip_4__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Strip_4__0__HSIOM_MASK 0x00000F00u
#define Strip_4__0__HSIOM_SHIFT 8u
#define Strip_4__0__INTCFG CYREG_PRT1_INTCFG
#define Strip_4__0__INTSTAT CYREG_PRT1_INTSTAT
#define Strip_4__0__MASK 0x04u
#define Strip_4__0__OUT_SEL CYREG_UDB_PA1_CFG10
#define Strip_4__0__OUT_SEL_SHIFT 4u
#define Strip_4__0__OUT_SEL_VAL 1u
#define Strip_4__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Strip_4__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Strip_4__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Strip_4__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Strip_4__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Strip_4__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Strip_4__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Strip_4__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Strip_4__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Strip_4__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Strip_4__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Strip_4__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Strip_4__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Strip_4__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Strip_4__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Strip_4__0__PC CYREG_PRT1_PC
#define Strip_4__0__PC2 CYREG_PRT1_PC2
#define Strip_4__0__PORT 1u
#define Strip_4__0__PS CYREG_PRT1_PS
#define Strip_4__0__SHIFT 2
#define Strip_4__DR CYREG_PRT1_DR
#define Strip_4__INTCFG CYREG_PRT1_INTCFG
#define Strip_4__INTSTAT CYREG_PRT1_INTSTAT
#define Strip_4__MASK 0x04u
#define Strip_4__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Strip_4__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Strip_4__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Strip_4__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Strip_4__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Strip_4__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Strip_4__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Strip_4__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Strip_4__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Strip_4__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Strip_4__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Strip_4__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Strip_4__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Strip_4__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Strip_4__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Strip_4__PC CYREG_PRT1_PC
#define Strip_4__PC2 CYREG_PRT1_PC2
#define Strip_4__PORT 1u
#define Strip_4__PS CYREG_PRT1_PS
#define Strip_4__SHIFT 2

/* Strip_5 */
#define Strip_5__0__DM__MASK 0x38u
#define Strip_5__0__DM__SHIFT 3
#define Strip_5__0__DR CYREG_PRT1_DR
#define Strip_5__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Strip_5__0__HSIOM_MASK 0x000000F0u
#define Strip_5__0__HSIOM_SHIFT 4u
#define Strip_5__0__INTCFG CYREG_PRT1_INTCFG
#define Strip_5__0__INTSTAT CYREG_PRT1_INTSTAT
#define Strip_5__0__MASK 0x02u
#define Strip_5__0__OUT_SEL CYREG_UDB_PA1_CFG10
#define Strip_5__0__OUT_SEL_SHIFT 2u
#define Strip_5__0__OUT_SEL_VAL 3u
#define Strip_5__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Strip_5__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Strip_5__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Strip_5__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Strip_5__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Strip_5__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Strip_5__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Strip_5__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Strip_5__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Strip_5__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Strip_5__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Strip_5__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Strip_5__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Strip_5__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Strip_5__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Strip_5__0__PC CYREG_PRT1_PC
#define Strip_5__0__PC2 CYREG_PRT1_PC2
#define Strip_5__0__PORT 1u
#define Strip_5__0__PS CYREG_PRT1_PS
#define Strip_5__0__SHIFT 1
#define Strip_5__DR CYREG_PRT1_DR
#define Strip_5__INTCFG CYREG_PRT1_INTCFG
#define Strip_5__INTSTAT CYREG_PRT1_INTSTAT
#define Strip_5__MASK 0x02u
#define Strip_5__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Strip_5__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Strip_5__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Strip_5__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Strip_5__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Strip_5__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Strip_5__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Strip_5__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Strip_5__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Strip_5__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Strip_5__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Strip_5__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Strip_5__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Strip_5__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Strip_5__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Strip_5__PC CYREG_PRT1_PC
#define Strip_5__PC2 CYREG_PRT1_PC2
#define Strip_5__PORT 1u
#define Strip_5__PS CYREG_PRT1_PS
#define Strip_5__SHIFT 1

/* Strip_6 */
#define Strip_6__0__DM__MASK 0x07u
#define Strip_6__0__DM__SHIFT 0
#define Strip_6__0__DR CYREG_PRT1_DR
#define Strip_6__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Strip_6__0__HSIOM_MASK 0x0000000Fu
#define Strip_6__0__HSIOM_SHIFT 0u
#define Strip_6__0__INTCFG CYREG_PRT1_INTCFG
#define Strip_6__0__INTSTAT CYREG_PRT1_INTSTAT
#define Strip_6__0__MASK 0x01u
#define Strip_6__0__OUT_SEL CYREG_UDB_PA1_CFG10
#define Strip_6__0__OUT_SEL_SHIFT 0u
#define Strip_6__0__OUT_SEL_VAL 2u
#define Strip_6__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Strip_6__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Strip_6__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Strip_6__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Strip_6__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Strip_6__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Strip_6__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Strip_6__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Strip_6__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Strip_6__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Strip_6__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Strip_6__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Strip_6__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Strip_6__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Strip_6__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Strip_6__0__PC CYREG_PRT1_PC
#define Strip_6__0__PC2 CYREG_PRT1_PC2
#define Strip_6__0__PORT 1u
#define Strip_6__0__PS CYREG_PRT1_PS
#define Strip_6__0__SHIFT 0
#define Strip_6__DR CYREG_PRT1_DR
#define Strip_6__INTCFG CYREG_PRT1_INTCFG
#define Strip_6__INTSTAT CYREG_PRT1_INTSTAT
#define Strip_6__MASK 0x01u
#define Strip_6__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Strip_6__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Strip_6__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Strip_6__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Strip_6__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Strip_6__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Strip_6__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Strip_6__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Strip_6__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Strip_6__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Strip_6__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Strip_6__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Strip_6__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Strip_6__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Strip_6__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Strip_6__PC CYREG_PRT1_PC
#define Strip_6__PC2 CYREG_PRT1_PC2
#define Strip_6__PORT 1u
#define Strip_6__PS CYREG_PRT1_PS
#define Strip_6__SHIFT 0

/* Strip_7 */
#define Strip_7__0__DM__MASK 0xE00000u
#define Strip_7__0__DM__SHIFT 21
#define Strip_7__0__DR CYREG_PRT0_DR
#define Strip_7__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Strip_7__0__HSIOM_MASK 0xF0000000u
#define Strip_7__0__HSIOM_SHIFT 28u
#define Strip_7__0__INTCFG CYREG_PRT0_INTCFG
#define Strip_7__0__INTSTAT CYREG_PRT0_INTSTAT
#define Strip_7__0__MASK 0x80u
#define Strip_7__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define Strip_7__0__OUT_SEL_SHIFT 14u
#define Strip_7__0__OUT_SEL_VAL 2u
#define Strip_7__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Strip_7__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Strip_7__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Strip_7__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Strip_7__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Strip_7__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Strip_7__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Strip_7__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Strip_7__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Strip_7__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Strip_7__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Strip_7__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Strip_7__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Strip_7__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Strip_7__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Strip_7__0__PC CYREG_PRT0_PC
#define Strip_7__0__PC2 CYREG_PRT0_PC2
#define Strip_7__0__PORT 0u
#define Strip_7__0__PS CYREG_PRT0_PS
#define Strip_7__0__SHIFT 7
#define Strip_7__DR CYREG_PRT0_DR
#define Strip_7__INTCFG CYREG_PRT0_INTCFG
#define Strip_7__INTSTAT CYREG_PRT0_INTSTAT
#define Strip_7__MASK 0x80u
#define Strip_7__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Strip_7__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Strip_7__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Strip_7__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Strip_7__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Strip_7__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Strip_7__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Strip_7__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Strip_7__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Strip_7__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Strip_7__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Strip_7__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Strip_7__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Strip_7__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Strip_7__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Strip_7__PC CYREG_PRT0_PC
#define Strip_7__PC2 CYREG_PRT0_PC2
#define Strip_7__PORT 0u
#define Strip_7__PS CYREG_PRT0_PS
#define Strip_7__SHIFT 7

/* Strip_8 */
#define Strip_8__0__DM__MASK 0x1C0u
#define Strip_8__0__DM__SHIFT 6
#define Strip_8__0__DR CYREG_PRT2_DR
#define Strip_8__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Strip_8__0__HSIOM_MASK 0x00000F00u
#define Strip_8__0__HSIOM_SHIFT 8u
#define Strip_8__0__INTCFG CYREG_PRT2_INTCFG
#define Strip_8__0__INTSTAT CYREG_PRT2_INTSTAT
#define Strip_8__0__MASK 0x04u
#define Strip_8__0__OUT_SEL CYREG_UDB_PA2_CFG10
#define Strip_8__0__OUT_SEL_SHIFT 4u
#define Strip_8__0__OUT_SEL_VAL 2u
#define Strip_8__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Strip_8__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Strip_8__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Strip_8__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Strip_8__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Strip_8__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Strip_8__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Strip_8__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Strip_8__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Strip_8__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Strip_8__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Strip_8__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Strip_8__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Strip_8__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Strip_8__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Strip_8__0__PC CYREG_PRT2_PC
#define Strip_8__0__PC2 CYREG_PRT2_PC2
#define Strip_8__0__PORT 2u
#define Strip_8__0__PS CYREG_PRT2_PS
#define Strip_8__0__SHIFT 2
#define Strip_8__DR CYREG_PRT2_DR
#define Strip_8__INTCFG CYREG_PRT2_INTCFG
#define Strip_8__INTSTAT CYREG_PRT2_INTSTAT
#define Strip_8__MASK 0x04u
#define Strip_8__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Strip_8__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Strip_8__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Strip_8__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Strip_8__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Strip_8__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Strip_8__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Strip_8__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Strip_8__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Strip_8__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Strip_8__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Strip_8__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Strip_8__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Strip_8__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Strip_8__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Strip_8__PC CYREG_PRT2_PC
#define Strip_8__PC2 CYREG_PRT2_PC2
#define Strip_8__PORT 2u
#define Strip_8__PS CYREG_PRT2_PS
#define Strip_8__SHIFT 2

/* Strip_9 */
#define Strip_9__0__DM__MASK 0xE00u
#define Strip_9__0__DM__SHIFT 9
#define Strip_9__0__DR CYREG_PRT2_DR
#define Strip_9__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Strip_9__0__HSIOM_MASK 0x0000F000u
#define Strip_9__0__HSIOM_SHIFT 12u
#define Strip_9__0__INTCFG CYREG_PRT2_INTCFG
#define Strip_9__0__INTSTAT CYREG_PRT2_INTSTAT
#define Strip_9__0__MASK 0x08u
#define Strip_9__0__OUT_SEL CYREG_UDB_PA2_CFG10
#define Strip_9__0__OUT_SEL_SHIFT 6u
#define Strip_9__0__OUT_SEL_VAL 1u
#define Strip_9__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Strip_9__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Strip_9__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Strip_9__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Strip_9__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Strip_9__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Strip_9__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Strip_9__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Strip_9__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Strip_9__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Strip_9__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Strip_9__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Strip_9__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Strip_9__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Strip_9__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Strip_9__0__PC CYREG_PRT2_PC
#define Strip_9__0__PC2 CYREG_PRT2_PC2
#define Strip_9__0__PORT 2u
#define Strip_9__0__PS CYREG_PRT2_PS
#define Strip_9__0__SHIFT 3
#define Strip_9__DR CYREG_PRT2_DR
#define Strip_9__INTCFG CYREG_PRT2_INTCFG
#define Strip_9__INTSTAT CYREG_PRT2_INTSTAT
#define Strip_9__MASK 0x08u
#define Strip_9__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Strip_9__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Strip_9__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Strip_9__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Strip_9__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Strip_9__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Strip_9__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Strip_9__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Strip_9__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Strip_9__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Strip_9__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Strip_9__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Strip_9__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Strip_9__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Strip_9__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Strip_9__PC CYREG_PRT2_PC
#define Strip_9__PC2 CYREG_PRT2_PC2
#define Strip_9__PORT 2u
#define Strip_9__PS CYREG_PRT2_PS
#define Strip_9__SHIFT 3

/* Strip_10 */
#define Strip_10__0__DM__MASK 0x7000u
#define Strip_10__0__DM__SHIFT 12
#define Strip_10__0__DR CYREG_PRT2_DR
#define Strip_10__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Strip_10__0__HSIOM_MASK 0x000F0000u
#define Strip_10__0__HSIOM_SHIFT 16u
#define Strip_10__0__INTCFG CYREG_PRT2_INTCFG
#define Strip_10__0__INTSTAT CYREG_PRT2_INTSTAT
#define Strip_10__0__MASK 0x10u
#define Strip_10__0__OUT_SEL CYREG_UDB_PA2_CFG10
#define Strip_10__0__OUT_SEL_SHIFT 8u
#define Strip_10__0__OUT_SEL_VAL 0u
#define Strip_10__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Strip_10__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Strip_10__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Strip_10__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Strip_10__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Strip_10__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Strip_10__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Strip_10__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Strip_10__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Strip_10__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Strip_10__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Strip_10__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Strip_10__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Strip_10__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Strip_10__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Strip_10__0__PC CYREG_PRT2_PC
#define Strip_10__0__PC2 CYREG_PRT2_PC2
#define Strip_10__0__PORT 2u
#define Strip_10__0__PS CYREG_PRT2_PS
#define Strip_10__0__SHIFT 4
#define Strip_10__DR CYREG_PRT2_DR
#define Strip_10__INTCFG CYREG_PRT2_INTCFG
#define Strip_10__INTSTAT CYREG_PRT2_INTSTAT
#define Strip_10__MASK 0x10u
#define Strip_10__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Strip_10__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Strip_10__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Strip_10__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Strip_10__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Strip_10__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Strip_10__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Strip_10__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Strip_10__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Strip_10__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Strip_10__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Strip_10__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Strip_10__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Strip_10__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Strip_10__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Strip_10__PC CYREG_PRT2_PC
#define Strip_10__PC2 CYREG_PRT2_PC2
#define Strip_10__PORT 2u
#define Strip_10__PS CYREG_PRT2_PS
#define Strip_10__SHIFT 4

/* Strip_11 */
#define Strip_11__0__DM__MASK 0x38000u
#define Strip_11__0__DM__SHIFT 15
#define Strip_11__0__DR CYREG_PRT2_DR
#define Strip_11__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Strip_11__0__HSIOM_MASK 0x00F00000u
#define Strip_11__0__HSIOM_SHIFT 20u
#define Strip_11__0__INTCFG CYREG_PRT2_INTCFG
#define Strip_11__0__INTSTAT CYREG_PRT2_INTSTAT
#define Strip_11__0__MASK 0x20u
#define Strip_11__0__OUT_SEL CYREG_UDB_PA2_CFG10
#define Strip_11__0__OUT_SEL_SHIFT 10u
#define Strip_11__0__OUT_SEL_VAL 1u
#define Strip_11__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Strip_11__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Strip_11__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Strip_11__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Strip_11__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Strip_11__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Strip_11__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Strip_11__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Strip_11__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Strip_11__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Strip_11__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Strip_11__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Strip_11__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Strip_11__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Strip_11__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Strip_11__0__PC CYREG_PRT2_PC
#define Strip_11__0__PC2 CYREG_PRT2_PC2
#define Strip_11__0__PORT 2u
#define Strip_11__0__PS CYREG_PRT2_PS
#define Strip_11__0__SHIFT 5
#define Strip_11__DR CYREG_PRT2_DR
#define Strip_11__INTCFG CYREG_PRT2_INTCFG
#define Strip_11__INTSTAT CYREG_PRT2_INTSTAT
#define Strip_11__MASK 0x20u
#define Strip_11__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Strip_11__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Strip_11__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Strip_11__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Strip_11__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Strip_11__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Strip_11__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Strip_11__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Strip_11__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Strip_11__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Strip_11__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Strip_11__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Strip_11__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Strip_11__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Strip_11__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Strip_11__PC CYREG_PRT2_PC
#define Strip_11__PC2 CYREG_PRT2_PC2
#define Strip_11__PORT 2u
#define Strip_11__PS CYREG_PRT2_PS
#define Strip_11__SHIFT 5

/* StripLights_B_WS2811 */
#define StripLights_B_WS2811_ctrl__0__MASK 0x01u
#define StripLights_B_WS2811_ctrl__0__POS 0
#define StripLights_B_WS2811_ctrl__16BIT_CONTROL_AUX_CTL_REG CYREG_UDB_W16_ACTL_02
#define StripLights_B_WS2811_ctrl__16BIT_CONTROL_CONTROL_REG CYREG_UDB_W16_CTL_02
#define StripLights_B_WS2811_ctrl__16BIT_CONTROL_COUNT_REG CYREG_UDB_W16_CTL_02
#define StripLights_B_WS2811_ctrl__16BIT_COUNT_CONTROL_REG CYREG_UDB_W16_CTL_02
#define StripLights_B_WS2811_ctrl__16BIT_COUNT_COUNT_REG CYREG_UDB_W16_CTL_02
#define StripLights_B_WS2811_ctrl__16BIT_MASK_MASK_REG CYREG_UDB_W16_MSK_02
#define StripLights_B_WS2811_ctrl__16BIT_MASK_PERIOD_REG CYREG_UDB_W16_MSK_02
#define StripLights_B_WS2811_ctrl__16BIT_PERIOD_MASK_REG CYREG_UDB_W16_MSK_02
#define StripLights_B_WS2811_ctrl__16BIT_PERIOD_PERIOD_REG CYREG_UDB_W16_MSK_02
#define StripLights_B_WS2811_ctrl__3__MASK 0x08u
#define StripLights_B_WS2811_ctrl__3__POS 3
#define StripLights_B_WS2811_ctrl__4__MASK 0x10u
#define StripLights_B_WS2811_ctrl__4__POS 4
#define StripLights_B_WS2811_ctrl__5__MASK 0x20u
#define StripLights_B_WS2811_ctrl__5__POS 5
#define StripLights_B_WS2811_ctrl__CONTROL_AUX_CTL_REG CYREG_UDB_W8_ACTL_02
#define StripLights_B_WS2811_ctrl__CONTROL_REG CYREG_UDB_W8_CTL_02
#define StripLights_B_WS2811_ctrl__CONTROL_ST_REG CYREG_UDB_CAT16_CTL_ST_02
#define StripLights_B_WS2811_ctrl__COUNT_REG CYREG_UDB_W8_CTL_02
#define StripLights_B_WS2811_ctrl__COUNT_ST_REG CYREG_UDB_CAT16_CTL_ST_02
#define StripLights_B_WS2811_ctrl__MASK 0x39u
#define StripLights_B_WS2811_ctrl__MASK_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define StripLights_B_WS2811_ctrl__PER_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define StripLights_B_WS2811_ctrl__PERIOD_REG CYREG_UDB_W8_MSK_02
#define StripLights_B_WS2811_dshifter_u0__16BIT_A0_REG CYREG_UDB_W16_A0_02
#define StripLights_B_WS2811_dshifter_u0__16BIT_A1_REG CYREG_UDB_W16_A1_02
#define StripLights_B_WS2811_dshifter_u0__16BIT_D0_REG CYREG_UDB_W16_D0_02
#define StripLights_B_WS2811_dshifter_u0__16BIT_D1_REG CYREG_UDB_W16_D1_02
#define StripLights_B_WS2811_dshifter_u0__16BIT_DP_AUX_CTL_REG CYREG_UDB_W16_ACTL_02
#define StripLights_B_WS2811_dshifter_u0__16BIT_F0_REG CYREG_UDB_W16_F0_02
#define StripLights_B_WS2811_dshifter_u0__16BIT_F1_REG CYREG_UDB_W16_F1_02
#define StripLights_B_WS2811_dshifter_u0__A0_A1_REG CYREG_UDB_CAT16_A_02
#define StripLights_B_WS2811_dshifter_u0__A0_REG CYREG_UDB_W8_A0_02
#define StripLights_B_WS2811_dshifter_u0__A1_REG CYREG_UDB_W8_A1_02
#define StripLights_B_WS2811_dshifter_u0__D0_D1_REG CYREG_UDB_CAT16_D_02
#define StripLights_B_WS2811_dshifter_u0__D0_REG CYREG_UDB_W8_D0_02
#define StripLights_B_WS2811_dshifter_u0__D1_REG CYREG_UDB_W8_D1_02
#define StripLights_B_WS2811_dshifter_u0__DP_AUX_CTL_REG CYREG_UDB_W8_ACTL_02
#define StripLights_B_WS2811_dshifter_u0__F0_F1_REG CYREG_UDB_CAT16_F_02
#define StripLights_B_WS2811_dshifter_u0__F0_REG CYREG_UDB_W8_F0_02
#define StripLights_B_WS2811_dshifter_u0__F1_REG CYREG_UDB_W8_F1_02
#define StripLights_B_WS2811_dshifter_u0__MSK_DP_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define StripLights_B_WS2811_dshifter_u0__PER_DP_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define StripLights_B_WS2811_pwm8_u0__16BIT_A0_REG CYREG_UDB_W16_A0_01
#define StripLights_B_WS2811_pwm8_u0__16BIT_A1_REG CYREG_UDB_W16_A1_01
#define StripLights_B_WS2811_pwm8_u0__16BIT_D0_REG CYREG_UDB_W16_D0_01
#define StripLights_B_WS2811_pwm8_u0__16BIT_D1_REG CYREG_UDB_W16_D1_01
#define StripLights_B_WS2811_pwm8_u0__16BIT_DP_AUX_CTL_REG CYREG_UDB_W16_ACTL_01
#define StripLights_B_WS2811_pwm8_u0__16BIT_F0_REG CYREG_UDB_W16_F0_01
#define StripLights_B_WS2811_pwm8_u0__16BIT_F1_REG CYREG_UDB_W16_F1_01
#define StripLights_B_WS2811_pwm8_u0__A0_A1_REG CYREG_UDB_CAT16_A_01
#define StripLights_B_WS2811_pwm8_u0__A0_REG CYREG_UDB_W8_A0_01
#define StripLights_B_WS2811_pwm8_u0__A1_REG CYREG_UDB_W8_A1_01
#define StripLights_B_WS2811_pwm8_u0__D0_D1_REG CYREG_UDB_CAT16_D_01
#define StripLights_B_WS2811_pwm8_u0__D0_REG CYREG_UDB_W8_D0_01
#define StripLights_B_WS2811_pwm8_u0__D1_REG CYREG_UDB_W8_D1_01
#define StripLights_B_WS2811_pwm8_u0__DP_AUX_CTL_REG CYREG_UDB_W8_ACTL_01
#define StripLights_B_WS2811_pwm8_u0__F0_F1_REG CYREG_UDB_CAT16_F_01
#define StripLights_B_WS2811_pwm8_u0__F0_REG CYREG_UDB_W8_F0_01
#define StripLights_B_WS2811_pwm8_u0__F1_REG CYREG_UDB_W8_F1_01
#define StripLights_B_WS2811_StatusReg__0__MASK 0x01u
#define StripLights_B_WS2811_StatusReg__0__POS 0
#define StripLights_B_WS2811_StatusReg__1__MASK 0x02u
#define StripLights_B_WS2811_StatusReg__1__POS 1
#define StripLights_B_WS2811_StatusReg__16BIT_STATUS_AUX_CTL_REG CYREG_UDB_W16_ACTL_02
#define StripLights_B_WS2811_StatusReg__16BIT_STATUS_REG CYREG_UDB_W16_ST_02
#define StripLights_B_WS2811_StatusReg__6__MASK 0x40u
#define StripLights_B_WS2811_StatusReg__6__POS 6
#define StripLights_B_WS2811_StatusReg__7__MASK 0x80u
#define StripLights_B_WS2811_StatusReg__7__POS 7
#define StripLights_B_WS2811_StatusReg__MASK 0xC3u
#define StripLights_B_WS2811_StatusReg__MASK_REG CYREG_UDB_W8_MSK_02
#define StripLights_B_WS2811_StatusReg__MASK_ST_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define StripLights_B_WS2811_StatusReg__PER_ST_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define StripLights_B_WS2811_StatusReg__STATUS_AUX_CTL_REG CYREG_UDB_W8_ACTL_02
#define StripLights_B_WS2811_StatusReg__STATUS_CNT_REG CYREG_UDB_CAT16_CTL_ST_02
#define StripLights_B_WS2811_StatusReg__STATUS_CONTROL_REG CYREG_UDB_CAT16_CTL_ST_02
#define StripLights_B_WS2811_StatusReg__STATUS_REG CYREG_UDB_W8_ST_02

/* StripLights_cisr */
#define StripLights_cisr__INTC_CLR_EN_REG CYREG_CM0_ICER
#define StripLights_cisr__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define StripLights_cisr__INTC_MASK 0x01u
#define StripLights_cisr__INTC_NUMBER 0u
#define StripLights_cisr__INTC_PRIOR_MASK 0xC0u
#define StripLights_cisr__INTC_PRIOR_NUM 3u
#define StripLights_cisr__INTC_PRIOR_REG CYREG_CM0_IPR0
#define StripLights_cisr__INTC_SET_EN_REG CYREG_CM0_ISER
#define StripLights_cisr__INTC_SET_PD_REG CYREG_CM0_ISPR

/* StripLights_fisr */
#define StripLights_fisr__INTC_CLR_EN_REG CYREG_CM0_ICER
#define StripLights_fisr__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define StripLights_fisr__INTC_MASK 0x04u
#define StripLights_fisr__INTC_NUMBER 2u
#define StripLights_fisr__INTC_PRIOR_MASK 0xC00000u
#define StripLights_fisr__INTC_PRIOR_NUM 3u
#define StripLights_fisr__INTC_PRIOR_REG CYREG_CM0_IPR0
#define StripLights_fisr__INTC_SET_EN_REG CYREG_CM0_ISER
#define StripLights_fisr__INTC_SET_PD_REG CYREG_CM0_ISPR

/* StripLights_StringSel */
#define StripLights_StringSel_Sync_ctrl_reg__0__MASK 0x01u
#define StripLights_StringSel_Sync_ctrl_reg__0__POS 0
#define StripLights_StringSel_Sync_ctrl_reg__1__MASK 0x02u
#define StripLights_StringSel_Sync_ctrl_reg__1__POS 1
#define StripLights_StringSel_Sync_ctrl_reg__16BIT_CONTROL_AUX_CTL_REG CYREG_UDB_W16_ACTL_00
#define StripLights_StringSel_Sync_ctrl_reg__16BIT_CONTROL_CONTROL_REG CYREG_UDB_W16_CTL_00
#define StripLights_StringSel_Sync_ctrl_reg__16BIT_CONTROL_COUNT_REG CYREG_UDB_W16_CTL_00
#define StripLights_StringSel_Sync_ctrl_reg__16BIT_COUNT_CONTROL_REG CYREG_UDB_W16_CTL_00
#define StripLights_StringSel_Sync_ctrl_reg__16BIT_COUNT_COUNT_REG CYREG_UDB_W16_CTL_00
#define StripLights_StringSel_Sync_ctrl_reg__16BIT_MASK_MASK_REG CYREG_UDB_W16_MSK_00
#define StripLights_StringSel_Sync_ctrl_reg__16BIT_MASK_PERIOD_REG CYREG_UDB_W16_MSK_00
#define StripLights_StringSel_Sync_ctrl_reg__16BIT_PERIOD_MASK_REG CYREG_UDB_W16_MSK_00
#define StripLights_StringSel_Sync_ctrl_reg__16BIT_PERIOD_PERIOD_REG CYREG_UDB_W16_MSK_00
#define StripLights_StringSel_Sync_ctrl_reg__2__MASK 0x04u
#define StripLights_StringSel_Sync_ctrl_reg__2__POS 2
#define StripLights_StringSel_Sync_ctrl_reg__3__MASK 0x08u
#define StripLights_StringSel_Sync_ctrl_reg__3__POS 3
#define StripLights_StringSel_Sync_ctrl_reg__32BIT_CONTROL_AUX_CTL_REG CYREG_UDB_W32_ACTL_00
#define StripLights_StringSel_Sync_ctrl_reg__32BIT_CONTROL_REG CYREG_UDB_W32_CTL_00
#define StripLights_StringSel_Sync_ctrl_reg__32BIT_COUNT_REG CYREG_UDB_W32_CTL_00
#define StripLights_StringSel_Sync_ctrl_reg__32BIT_PERIOD_REG CYREG_UDB_W32_MSK_00
#define StripLights_StringSel_Sync_ctrl_reg__CONTROL_AUX_CTL_REG CYREG_UDB_W8_ACTL_00
#define StripLights_StringSel_Sync_ctrl_reg__CONTROL_REG CYREG_UDB_W8_CTL_00
#define StripLights_StringSel_Sync_ctrl_reg__CONTROL_ST_REG CYREG_UDB_CAT16_CTL_ST_00
#define StripLights_StringSel_Sync_ctrl_reg__COUNT_REG CYREG_UDB_W8_CTL_00
#define StripLights_StringSel_Sync_ctrl_reg__COUNT_ST_REG CYREG_UDB_CAT16_CTL_ST_00
#define StripLights_StringSel_Sync_ctrl_reg__MASK 0x0Fu
#define StripLights_StringSel_Sync_ctrl_reg__MASK_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_00
#define StripLights_StringSel_Sync_ctrl_reg__PER_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_00
#define StripLights_StringSel_Sync_ctrl_reg__PERIOD_REG CYREG_UDB_W8_MSK_00

/* Miscellaneous */
#define CY_PROJECT_NAME "Striplight_bootloadable"
#define CY_VERSION "PSoC Creator  3.3"
#define CYDEV_BCLK__HFCLK__HZ 24000000U
#define CYDEV_BCLK__HFCLK__KHZ 24000U
#define CYDEV_BCLK__HFCLK__MHZ 24U
#define CYDEV_BCLK__SYSCLK__HZ 24000000U
#define CYDEV_BCLK__SYSCLK__KHZ 24000U
#define CYDEV_BCLK__SYSCLK__MHZ 24U
#define CYDEV_CHIP_DIE_LEOPARD 1u
#define CYDEV_CHIP_DIE_PANTHER 18u
#define CYDEV_CHIP_DIE_PSOC4A 10u
#define CYDEV_CHIP_DIE_PSOC5LP 17u
#define CYDEV_CHIP_DIE_TMA4 2u
#define CYDEV_CHIP_DIE_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_PSOC3 1u
#define CYDEV_CHIP_FAMILY_PSOC4 2u
#define CYDEV_CHIP_FAMILY_PSOC5 3u
#define CYDEV_CHIP_FAMILY_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_USED CYDEV_CHIP_FAMILY_PSOC4
#define CYDEV_CHIP_JTAG_ID 0x04C81193u
#define CYDEV_CHIP_MEMBER_3A 1u
#define CYDEV_CHIP_MEMBER_4A 10u
#define CYDEV_CHIP_MEMBER_4C 15u
#define CYDEV_CHIP_MEMBER_4D 6u
#define CYDEV_CHIP_MEMBER_4E 4u
#define CYDEV_CHIP_MEMBER_4F 11u
#define CYDEV_CHIP_MEMBER_4G 2u
#define CYDEV_CHIP_MEMBER_4H 9u
#define CYDEV_CHIP_MEMBER_4I 14u
#define CYDEV_CHIP_MEMBER_4J 7u
#define CYDEV_CHIP_MEMBER_4K 8u
#define CYDEV_CHIP_MEMBER_4L 13u
#define CYDEV_CHIP_MEMBER_4M 12u
#define CYDEV_CHIP_MEMBER_4N 5u
#define CYDEV_CHIP_MEMBER_4U 3u
#define CYDEV_CHIP_MEMBER_5A 17u
#define CYDEV_CHIP_MEMBER_5B 16u
#define CYDEV_CHIP_MEMBER_UNKNOWN 0u
#define CYDEV_CHIP_MEMBER_USED CYDEV_CHIP_MEMBER_4A
#define CYDEV_CHIP_DIE_EXPECT CYDEV_CHIP_MEMBER_USED
#define CYDEV_CHIP_DIE_ACTUAL CYDEV_CHIP_DIE_EXPECT
#define CYDEV_CHIP_REV_LEOPARD_ES1 0u
#define CYDEV_CHIP_REV_LEOPARD_ES2 1u
#define CYDEV_CHIP_REV_LEOPARD_ES3 3u
#define CYDEV_CHIP_REV_LEOPARD_PRODUCTION 3u
#define CYDEV_CHIP_REV_PANTHER_ES0 0u
#define CYDEV_CHIP_REV_PANTHER_ES1 1u
#define CYDEV_CHIP_REV_PANTHER_PRODUCTION 1u
#define CYDEV_CHIP_REV_PSOC4A_ES0 17u
#define CYDEV_CHIP_REV_PSOC4A_PRODUCTION 17u
#define CYDEV_CHIP_REV_PSOC5LP_ES0 0u
#define CYDEV_CHIP_REV_PSOC5LP_PRODUCTION 0u
#define CYDEV_CHIP_REV_TMA4_ES 17u
#define CYDEV_CHIP_REV_TMA4_ES2 33u
#define CYDEV_CHIP_REV_TMA4_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_3A_ES1 0u
#define CYDEV_CHIP_REVISION_3A_ES2 1u
#define CYDEV_CHIP_REVISION_3A_ES3 3u
#define CYDEV_CHIP_REVISION_3A_PRODUCTION 3u
#define CYDEV_CHIP_REVISION_4A_ES0 17u
#define CYDEV_CHIP_REVISION_4A_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4C_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4D_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4E_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION_256DMA 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION_256K 0u
#define CYDEV_CHIP_REVISION_4G_ES 17u
#define CYDEV_CHIP_REVISION_4G_ES2 33u
#define CYDEV_CHIP_REVISION_4G_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4H_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4I_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4J_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4K_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4L_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4M_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4N_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4U_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_5A_ES0 0u
#define CYDEV_CHIP_REVISION_5A_ES1 1u
#define CYDEV_CHIP_REVISION_5A_PRODUCTION 1u
#define CYDEV_CHIP_REVISION_5B_ES0 0u
#define CYDEV_CHIP_REVISION_5B_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_USED CYDEV_CHIP_REVISION_4A_PRODUCTION
#define CYDEV_CHIP_REV_EXPECT CYDEV_CHIP_REVISION_USED
#define CYDEV_CONFIG_READ_ACCELERATOR 1
#define CYDEV_CONFIG_UNUSED_IO_AllowButWarn 0
#define CYDEV_CONFIG_UNUSED_IO CYDEV_CONFIG_UNUSED_IO_AllowButWarn
#define CYDEV_CONFIG_UNUSED_IO_AllowWithInfo 1
#define CYDEV_CONFIG_UNUSED_IO_Disallowed 2
#define CYDEV_CONFIGURATION_COMPRESSED 1
#define CYDEV_CONFIGURATION_MODE_COMPRESSED 0
#define CYDEV_CONFIGURATION_MODE CYDEV_CONFIGURATION_MODE_COMPRESSED
#define CYDEV_CONFIGURATION_MODE_DMA 2
#define CYDEV_CONFIGURATION_MODE_UNCOMPRESSED 1
#define CYDEV_DEBUG_PROTECT_KILL 4
#define CYDEV_DEBUG_PROTECT_OPEN 1
#define CYDEV_DEBUG_PROTECT CYDEV_DEBUG_PROTECT_OPEN
#define CYDEV_DEBUG_PROTECT_PROTECTED 2
#define CYDEV_DEBUGGING_DPS_Disable 3
#define CYDEV_DEBUGGING_DPS CYDEV_DEBUGGING_DPS_Disable
#define CYDEV_DEBUGGING_DPS_SWD 2
#define CYDEV_DEBUGGING_ENABLE 0
#define CYDEV_DFT_SELECT_CLK0 1u
#define CYDEV_DFT_SELECT_CLK1 2u
#define CYDEV_HEAP_SIZE 0x0100
#define CYDEV_IMO_TRIMMED_BY_USB 0u
#define CYDEV_IMO_TRIMMED_BY_WCO 0u
#define CYDEV_IS_EXPORTING_CODE 0
#define CYDEV_IS_IMPORTING_CODE 0
#define CYDEV_PROJ_TYPE 2
#define CYDEV_PROJ_TYPE_BOOTLOADER 1
#define CYDEV_PROJ_TYPE_LAUNCHER 5
#define CYDEV_PROJ_TYPE_LOADABLE 2
#define CYDEV_PROJ_TYPE_LOADABLEANDBOOTLOADER 4
#define CYDEV_PROJ_TYPE_MULTIAPPBOOTLOADER 3
#define CYDEV_PROJ_TYPE_STANDARD 0
#define CYDEV_STACK_SIZE 0x0400
#define CYDEV_USE_BUNDLED_CMSIS 1
#define CYDEV_VARIABLE_VDDA 0
#define CYDEV_VDDA 5
#define CYDEV_VDDA_MV 5000
#define CYDEV_VDDD 5
#define CYDEV_VDDD_MV 5000
#define CYDEV_WDT_GENERATE_ISR 0u
#define CYIPBLOCK_M0S8_CTBM_VERSION 0
#define CYIPBLOCK_m0s8cpuss_VERSION 0
#define CYIPBLOCK_m0s8csd_VERSION 0
#define CYIPBLOCK_m0s8gpio2_VERSION 0
#define CYIPBLOCK_m0s8hsiom4a_VERSION 0
#define CYIPBLOCK_m0s8lcd_VERSION 0
#define CYIPBLOCK_m0s8lpcomp_VERSION 0
#define CYIPBLOCK_m0s8pclk_VERSION 0
#define CYIPBLOCK_m0s8sar_VERSION 0
#define CYIPBLOCK_m0s8scb_VERSION 0
#define CYIPBLOCK_m0s8srssv2_VERSION 1
#define CYIPBLOCK_m0s8tcpwm_VERSION 0
#define CYIPBLOCK_m0s8udbif_VERSION 0
#define CYIPBLOCK_S8_GPIO_VERSION 2
#define CYDEV_BOOTLOADER_ENABLE 0

#endif /* INCLUDED_CYFITTER_H */
